package dictionary;

import javax.swing.*;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionListener;
import java.awt.event.ActionListener;
import java.util.List;

/**
 * View layer for the Dictionary application (Swing UI).
 *
 * Responsibilities:
 * - Own and display Swing UI components
 * - Expose listener hooks so the Controller can respond to user actions
 * - Provide getters/setters for UI state (text fields, lists, details)
 *
 * This class contains NO business logic. All dictionary behavior lives in
 * {@link DictionaryService} and is coordinated by {@link DictionaryController}.
 */
public class DictionaryPanel {

    // Root panel (generated by GUI designer)
    private JPanel app;

    // North Panel
    private JTextField searchWordTextField;
    private JButton btn_find;
    private JButton btn_add;
    private JButton btn_delete;
    private JLabel searchWord;
    private JButton btn_exit;

    // Center Panel
    private JPanel search_panel;
    private JSplitPane splitMain;
    private JPanel listPanel;
    private JPanel detailsPanel;
    private JLabel word;
    private JTextField wordText;
    private JLabel pron;
    private JTextField pron_text_field;
    private JButton btn_audio;
    private JPanel pronPanel;
    private JLabel example;
    private JLabel def;
    private JLabel syn;
    private JScrollPane defScroll;
    private JTextArea defTextArea;
    private JScrollPane examScroll;
    private JTextArea examTextArea;
    private JScrollPane synScroll;
    private JTextArea synTextArea;
    private JPanel history;
    private JPanel detailsBtn;
    private JButton btn_edit;
    private JButton btn_clear;
    private JButton btn_save;
    private JScrollPane scroll;
    private JList<String> lstWords;
    private JPanel list_search;
    private JPanel fullListPanel;
    private JLabel searchWordList;
    private JTextField filter;

    // South Panel
    private JPanel historyPanel;
    private JLabel hist;
    private JButton btn_freq2;
    private JButton btn_clearHistory;
    private JButton btn_freq5;
    private JButton btn_freq4;
    private JButton btn_freq3;
    private JButton btn_freq1;
    private JLabel count;

    // Import/Export Buttons
    private JButton btn_export;
    private JButton btn_import;

    /**
     * Returns the root panel so it can be mounted into a JFrame.
     *
     * @return the root JPanel for this view
     */
    public JPanel getRoot() {
        return app;
    }

    // ----------------------------
    // Listener hooks (Controller wiring)
    // ----------------------------

    /**
     * Attaches a listener to the Find button.
     *
     * @param l ActionListener callback
     */
    public void onFind(ActionListener l) { btn_find.addActionListener(l); }

    /**
     * Attaches a listener to the Add button.
     *
     * @param l ActionListener callback
     */
    public void onAdd(ActionListener l) { btn_add.addActionListener(l); }

    /**
     * Attaches a listener to the Delete button.
     *
     * @param l ActionListener callback
     */
    public void onDelete(ActionListener l) { btn_delete.addActionListener(l); }

    /**
     * Attaches a listener to the Exit button.
     *
     * @param l ActionListener callback
     */
    public void onExit(ActionListener l) { btn_exit.addActionListener(l); }

    /**
     * Attaches a listener to the Audio button.
     *
     * @param l ActionListener callback
     */
    public void onAudio(ActionListener l) { btn_audio.addActionListener(l); }

    /**
     * Attaches a listener to the Edit button.
     *
     * @param l ActionListener callback
     */
    public void onEdit(ActionListener l) { btn_edit.addActionListener(l); }

    /**
     * Attaches a listener to the Clear button in the details panel.
     *
     * @param l ActionListener callback
     */
    public void onClear(ActionListener l) { btn_clear.addActionListener(l); }

    /**
     * Attaches a listener to the Save button in the details panel.
     *
     * @param l ActionListener callback
     */
    public void onSave(ActionListener l) { btn_save.addActionListener(l); }

    /**
     * Attaches a listener to Top-5 frequency button #1.
     *
     * @param l ActionListener callback
     */
    public void onFreq1(ActionListener l) { btn_freq1.addActionListener(l); }

    /**
     * Attaches a listener to Top-5 frequency button #2.
     *
     * @param l ActionListener callback
     */
    public void onFreq2(ActionListener l) { btn_freq2.addActionListener(l); }

    /**
     * Attaches a listener to Top-5 frequency button #3.
     *
     * @param l ActionListener callback
     */
    public void onFreq3(ActionListener l) { btn_freq3.addActionListener(l); }

    /**
     * Attaches a listener to Top-5 frequency button #4.
     *
     * @param l ActionListener callback
     */
    public void onFreq4(ActionListener l) { btn_freq4.addActionListener(l); }

    /**
     * Attaches a listener to Top-5 frequency button #5.
     *
     * @param l ActionListener callback
     */
    public void onFreq5(ActionListener l) { btn_freq5.addActionListener(l); }

    /**
     * Attaches a listener to the Clear History button.
     *
     * @param l ActionListener callback
     */
    public void onClearHist(ActionListener l) { btn_clearHistory.addActionListener(l); }

    /**
     * Attaches a listener to the Import button.
     *
     * @param l ActionListener callback
     */
    public void onImport(ActionListener l) { btn_import.addActionListener(l); }

    /**
     * Attaches a listener to the Export button.
     *
     * @param l ActionListener callback
     */
    public void onExport(ActionListener l) { btn_export.addActionListener(l); }

    /**
     * Attaches a listener for selection changes in the word list.
     *
     * @param l ListSelectionListener callback
     */
    public void onWordSelection(ListSelectionListener l) {
        lstWords.addListSelectionListener(l);
    }

    /**
     * Attaches a listener for changes in the prefix filter text field.
     *
     * @param l DocumentListener callback
     */
    public void onFilterChanged(DocumentListener l) {
        filter.getDocument().addDocumentListener(l);
    }

    // ----------------------------
    // Getters (inputs/state)
    // ----------------------------

    /**
     * Returns the current text in the search box.
     *
     * @return search word text
     */
    public String getSearchWord() { return searchWordTextField.getText(); }

    /**
     * Returns the current text in the prefix filter box.
     *
     * @return filter text
     */
    public String getFilterText() { return filter.getText(); }

    /**
     * Returns the currently selected word from the JList.
     *
     * @return selected word, or null if none selected
     */
    public String getSelectedWord() { return lstWords.getSelectedValue(); }

    // ----------------------------
    // Setters (UI updates)
    // ----------------------------

    /**
     * Updates the label that displays the total number of words.
     *
     * @param n total word count
     */
    public void setTotalCount(int n) { count.setText("Total Words: " + n); }

    /**
     * Replaces the JList contents with the provided words.
     *
     * @param words list of words to display
     */
    public void setSearchWordList(List<String> words){
        DefaultListModel<String> model = new DefaultListModel<>();
        for(String word : words){
            model.addElement(word);
        }
        lstWords.setModel(model);
    }

    /**
     * Selects a word in the JList if it exists.
     *
     * @param word word to select
     */
    public void selectWordInList(String word){
        ListModel<String> model = lstWords.getModel();
        for(int i = 0; i < model.getSize(); i++){
            if(word.equalsIgnoreCase(model.getElementAt(i))){
                lstWords.setSelectedIndex(i);
                lstWords.ensureIndexIsVisible(i);
                return;
            }
        }
    }

    /**
     * Populates the detail fields with the values from a dictionary entry.
     *
     * @param e dictionary entry to display
     */
    public void setDetails(dictionaryEntry e){
        wordText.setText(e.getWord());
        pron_text_field.setText(e.getPronounce());
        defTextArea.setText(e.getDefinition());
        examTextArea.setText(e.getExample());
        synTextArea.setText(String.join(", ", e.getSyn()));
    }

    /**
     * Updates the Top-5 buttons with the provided most searched words.
     * If fewer than 5 words are provided, remaining buttons are disabled.
     *
     * @param topWords list of top searched words
     */
    public void setTop5Buttons(List<String> topWords){
        JButton[] btns = { btn_freq1, btn_freq2, btn_freq3, btn_freq4, btn_freq5 };

        for (int i = 0; i < btns.length; i++) {
            if (topWords != null && i < topWords.size()) {
                btns[i].setText(topWords.get(i));
                btns[i].setEnabled(true);
            } else {
                btns[i].setText("-");
                btns[i].setEnabled(false);
            }
        }
    }

    /**
     * Returns the word stored in one of the Top-5 buttons.
     *
     * @param index button index (0–4)
     * @return word text if valid; otherwise null
     */
    public String getTopWordFromButton(int index) {
        JButton[] btns = { btn_freq1, btn_freq2, btn_freq3, btn_freq4, btn_freq5 };
        if (index < 0 || index >= btns.length) return null;

        String text = btns[index].getText();
        if (text == null || text.isBlank() || text.equals("-")) return null;

        return text.trim();
    }

    /**
     * Builds a dictionaryEntry from the current detail input fields.
     *
     * @return dictionaryEntry representing current form values
     */
    public dictionaryEntry getDetailsFromFields(){
        List<String> syns = List.of(synTextArea.getText().split("\\s*,\\s*"));

        return new dictionaryEntry(
                wordText.getText().trim(),
                pron_text_field.getText().trim(),
                defTextArea.getText().trim(),
                examTextArea.getText().trim(),
                syns
        );
    }

    /**
     * Clears all text fields in the details panel.
     */
    public void clearDetails() {
        wordText.setText("");
        pron_text_field.setText("");
        defTextArea.setText("");
        examTextArea.setText("");
        synTextArea.setText("");
    }

    /**
     * Toggles whether the details fields are editable.
     *
     * @param editing true to allow editing, false to lock the fields
     */
    public void setEditing(boolean editing){
        wordText.setEditable(editing);
        pron_text_field.setEditable(editing);
        defTextArea.setEditable(editing);
        examTextArea.setEditable(editing);
        synTextArea.setEditable(editing);
    }

    // ----------------------------
    // Dialog helpers
    // ----------------------------

    /**
     * Displays a confirmation dialog.
     *
     * @param message confirmation text
     * @return true if user clicked Yes; false otherwise
     */
    public boolean confirm(String message) {
        return JOptionPane.showConfirmDialog(app, message, "Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }

    /**
     * Displays an error dialog.
     *
     * @param message error text
     */
    public void showError(String message) {
        JOptionPane.showMessageDialog(app, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Prompts the user to confirm application exit.
     *
     * @return true if user confirms exit; false otherwise
     */
    public boolean confirmExit() {
        return JOptionPane.showConfirmDialog(
                getRoot(),
                "Exit the application?",
                "Confirm Exit",
                JOptionPane.YES_NO_OPTION
        ) == JOptionPane.YES_OPTION;
    }

    /**
     * Closes the top-level window containing this panel.
     */
    public void closeWindow() {
        java.awt.Window w = SwingUtilities.getWindowAncestor(getRoot());
        if (w != null) w.dispose();
    }

    /**
     * Opens a file chooser dialog to pick where to export dictionary data.
     *
     * @return selected file, or null if the user cancels
     */
    public java.io.File chooseExportFile() {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Export Dictionary");

        int result = chooser.showSaveDialog(getRoot());
        if (result == JFileChooser.APPROVE_OPTION) {
            return chooser.getSelectedFile();
        }
        return null;
    }

    /**
     * Clears the prefix filter text field.
     */
    public void clearFilter() {
        filter.setText("");
    }
}